# Generated by Django 4.2.1 on 2023-05-16 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_complaints_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='address',
            field=models.TextField(default='address'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AddField(
            model_name='complaints',
            name='pincode',
            field=models.CharField(default='689105', max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be a 6-digit number.', regex='^\\d{6}$')]),
        ),
    ]
