# Generated by Django 4.2.1 on 2023-05-16 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_complaints_address_complaints_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='police_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
