# Generated by Django 4.2.1 on 2023-05-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_policeuser_badge_number_alter_policeuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeuser',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
