# Generated by Django 4.2.1 on 2023-05-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_policeuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policeuser',
            name='password',
        ),
        migrations.AddField(
            model_name='policeuser',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='policeuser',
            name='district',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='policeuser',
            name='phonenumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='policeuser',
            name='station',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='policeuser',
            name='stationadmin',
            field=models.CharField(default='', max_length=30),
        ),
    ]
