# Generated by Django 4.2.1 on 2023-05-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_policeuser_password_policeuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeuser',
            name='adminposition',
            field=models.CharField(default='', max_length=30),
        ),
    ]
