# Generated by Django 4.2.1 on 2023-05-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_replay'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='replay',
            new_name='replays',
        ),
    ]
