# Generated by Django 4.2.1 on 2023-05-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_complaints_user_alter_complaints_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='crime_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=30)),
            ],
        ),
    ]
