# Generated by Django 4.2.1 on 2023-05-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_crime_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='fir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal_name', models.CharField(max_length=30)),
                ('criminal_address', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('crime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.crime_types')),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.policeuser')),
            ],
        ),
    ]
