# Generated by Django 4.2.1 on 2023-05-18 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_fir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replays',
            name='complaint',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.complaints'),
        ),
    ]
