# Generated by Django 4.2.1 on 2023-05-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_replays_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crime_types',
            old_name='station',
            new_name='ctypes',
        ),
    ]
